;; Handwritten graph reductions over a fixed-width wasm32 node layout.
;; The standalone build selects eight bytes. The C control uses twelve bytes.
;; Return before GC, scheduling, an unsupported primitive, or stack overflow.
;; The standalone WAT evaluator or C control resumes from the saved stack.
(module
  (import "support" "memory" (memory 0))
  (import "support" "stack" (global $stack_addr i32))
  (import "support" "stack_ptr" (global $sp_addr i32))
  (import "support" "stack_size" (global $stack_size_addr i32))
  (import "support" "glob_slice" (global $slice_addr i32))
  (import "support" "cells" (global $cells_addr i32))
  (import "support" "free_map" (global $map_addr i32))
  (import "support" "next_scan_index" (global $scan_addr i32))
  (import "support" "num_free" (global $free_addr i32))
  (import "support" "num_alloc" (global $alloc_addr i32))

  (import "support" "combB" (global $combB_addr i32))
  (import "support" "combC" (global $combC_addr i32))
  (import "support" "combK" (global $combK_addr i32))
  (import "support" "combK2" (global $combK2_addr i32))
  (import "support" "combK3" (global $combK3_addr i32))
  (import "support" "intTable" (global $ints_addr i32))
  (import "support" "red_bb" (global $red_bb_addr i32))
  (import "support" "red_z" (global $red_z_addr i32))
  (import "support" "red_r" (global $red_r_addr i32))
  (import "support" "red_k2" (global $red_k2_addr i32))
  (import "support" "red_k3" (global $red_k3_addr i32))
  (import "support" "red_k4" (global $red_k4_addr i32))
  (import "support" "red_ccb" (global $red_ccb_addr i32))

  ;; Build-time node stride. Binaryen folds this constant before linking.
  (global $node_bytes i32 (i32.const 12))

  ;; Read an argument from an application on the spine.
  (func $arg (param $stack i32) (param $sp i32) (param $offset i32) (result i32)
    (i32.load offset=4
      (i32.load
        (i32.add (local.get $stack)
          (i32.shl (i32.sub (local.get $sp) (local.get $offset)) (i32.const 2))))))

  ;; Allocate one application. The caller has checked the free-node count.
  ;; This function cannot collect or yield.
  (func $app (param $f i32) (param $a i32) (result i32)
    (local $map i32) (local $index i32) (local $word i32)
    (local $pos i32) (local $n i32)
    (local.set $map (i32.load (global.get $map_addr)))
    (local.set $index
      (i32.shr_u (i32.load (global.get $scan_addr)) (i32.const 5)))
    (block $found
      (loop $scan
        (local.set $word
          (i32.load (i32.add (local.get $map)
            (i32.shl (local.get $index) (i32.const 2)))))
        (br_if $found (local.get $word))
        (local.set $index (i32.add (local.get $index) (i32.const 1)))
        (br $scan)))
    (local.set $pos
      (i32.add (i32.shl (local.get $index) (i32.const 5))
        (i32.ctz (local.get $word))))
    (i32.store
      (i32.add (local.get $map) (i32.shl (local.get $index) (i32.const 2)))
      (i32.and (local.get $word) (i32.sub (local.get $word) (i32.const 1))))
    (i32.store (global.get $scan_addr) (local.get $pos))
    (i32.store (global.get $free_addr)
      (i32.sub (i32.load (global.get $free_addr)) (i32.const 1)))
    (i32.store (global.get $alloc_addr)
      (i32.add (i32.load (global.get $alloc_addr)) (i32.const 1)))
    (local.set $n
      (i32.add (i32.load (global.get $cells_addr))
        (i32.mul (local.get $pos) (global.get $node_bytes))))
    (i32.store (local.get $n) (local.get $f))
    (i32.store offset=4 (local.get $n) (local.get $a))
    (local.get $n))

  (func (export "reduce") (param $n i32) (param $base i32) (result i32)
    (local $stack i32) (local $sp i32) (local $limit i32) (local $slice i32)
    (local $ut i32) (local $tag i32) (local $old i32) (local $argc i32)
    (local $x i32) (local $y i32) (local $z i32) (local $w i32)
    (local $redex i32) (local $arity i32) (local $i i32)
    (local.set $stack (i32.load (global.get $stack_addr)))
    (local.set $sp (i32.load (global.get $sp_addr)))
    (local.set $limit
      (i32.sub (i32.load (global.get $stack_size_addr)) (i32.const 2)))
    (local.set $slice (i32.load (global.get $slice_addr)))
    (block $exit
      (loop $top
        (br_if $exit (i32.le_s (local.get $slice) (i32.const 1)))
        ;; Follow the application spine without allocating.
        (block $head
          (loop $descend
            (local.set $ut (i32.load (local.get $n)))
            (br_if $head (i32.and (local.get $ut) (i32.const 3)))
            (br_if $exit (i32.ge_s (local.get $sp) (local.get $limit)))
            (local.set $sp (i32.add (local.get $sp) (i32.const 1)))
            (i32.store
              (i32.add (local.get $stack) (i32.shl (local.get $sp) (i32.const 2)))
              (local.get $n))
            (local.set $n (local.get $ut))
            (br $descend)))
        ;; Charge indirection traversal to the scheduling slice. A cycle must
        ;; return control to the scheduler. Compress only a completed chain.
        (if (i32.eq (i32.and (local.get $ut) (i32.const 3)) (i32.const 2))
          (then
            (local.set $old (local.get $n))
            (loop $ind
              (local.set $n (i32.and (local.get $ut) (i32.const -4)))
              (local.set $ut (i32.load (local.get $n)))
              (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
              (br_if $exit (i32.le_s (local.get $slice) (i32.const 1)))
              (br_if $ind
                (i32.eq (i32.and (local.get $ut) (i32.const 3)) (i32.const 2))))
            (i32.store (local.get $old) (i32.or (local.get $n) (i32.const 2)))))
        ;; The C T_AP case consumes a slice step after an indirection.
        (if (i32.eqz (i32.and (local.get $ut) (i32.const 3)))
          (then
            (if (i32.ge_s (local.get $sp) (local.get $limit))
              (then (local.set $n (local.get $old)) (br $exit)))
            (local.set $sp (i32.add (local.get $sp) (i32.const 1)))
            (i32.store
              (i32.add (local.get $stack) (i32.shl (local.get $sp) (i32.const 2)))
              (local.get $n))
            (local.set $n (local.get $ut))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)))
        (local.set $tag (i32.shr_u (local.get $ut) (i32.const 2)))
        (local.set $argc (i32.sub (local.get $sp) (local.get $base)))
        (block $tagged
        (block $tuple
        (block $KA
        (block $KK
        (block $L
        (block $CCB
        (block $K4
        (block $K3
        (block $K2
        (block $J
        (block $Z
        (block $U
        (block $O
        (block $R
        (block $P
        (block $CC
        (block $BB
        (block $SS
        (block $Y
        (block $A
        (block $C
        (block $B
        (block $I
        (block $K
        (block $S
          (br_table $S $K $I $B $C $A $Y $SS $BB $CC $P $R $O $U $Z $J $K2 $K3 $K4 $CCB $L $KK $KA $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tuple $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $tagged $exit
            (i32.sub (local.get $tag) (i32.const 15)))
        )
        ;; S: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $x) (local.get $z)))
        (i32.store offset=4 (local.get $n) (call $app (local.get $y) (local.get $z)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; K: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.or (local.get $x) (i32.const 2)))
        (local.set $n (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; I: consume 1 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 1)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.or (local.get $x) (i32.const 2)))
        (local.set $n (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; B: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $x))
        (i32.store offset=4 (local.get $n) (call $app (local.get $y) (local.get $z)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; C: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $x) (local.get $z)))
        (i32.store offset=4 (local.get $n) (local.get $y))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; A: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.or (local.get $y) (i32.const 2)))
        (local.set $n (local.get $y))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; Y: consume 1 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 1)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $x))
        (i32.store offset=4 (local.get $n) (local.get $n))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; SS: consume 4 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 3)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $w (call $arg (local.get $stack) (local.get $sp) (i32.const 3)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $x) (call $app (local.get $y) (local.get $w))))
        (i32.store offset=4 (local.get $n) (call $app (local.get $z) (local.get $w)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 4))
          (then
            ;; BB: consume 4 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
            (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
            (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
            (local.set $w (call $arg (local.get $stack) (local.get $sp) (i32.const 3)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (call $app (local.get $x) (local.get $y)))
            (i32.store offset=4 (local.get $n) (call $app (local.get $z) (local.get $w)))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; BB: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.load (global.get $combB_addr)))
        (i32.store offset=4 (local.get $n) (call $app (local.get $x) (local.get $y)))
        (i32.store (global.get $red_bb_addr) (i32.add (i32.load (global.get $red_bb_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; CC: consume 4 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $w (call $arg (local.get $stack) (local.get $sp) (i32.const 3)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $x) (call $app (local.get $y) (local.get $w))))
        (i32.store offset=4 (local.get $n) (local.get $z))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; P: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $z) (local.get $x)))
        (i32.store offset=4 (local.get $n) (local.get $y))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 3))
          (then
            ;; R: consume 3 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
            (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
            (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (call $app (local.get $y) (local.get $z)))
            (i32.store offset=4 (local.get $n) (local.get $x))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; R: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (i32.load (global.get $combC_addr)) (local.get $y)))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (i32.store (global.get $red_r_addr) (i32.add (i32.load (global.get $red_r_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; O: consume 4 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $w (call $arg (local.get $stack) (local.get $sp) (i32.const 3)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $w) (local.get $x)))
        (i32.store offset=4 (local.get $n) (local.get $y))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; U: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $y))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 3))
          (then
            ;; Z: consume 3 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (local.get $x))
            (i32.store offset=4 (local.get $n) (local.get $y))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; Z: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 1)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.load (global.get $combK_addr)))
        (i32.store offset=4 (local.get $n) (call $app (local.get $x) (local.get $y)))
        (i32.store (global.get $red_z_addr) (i32.add (i32.load (global.get $red_z_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; J: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $z))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 3))
          (then
            ;; K2: consume 3 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (i32.or (local.get $x) (i32.const 2)))
            (local.set $n (local.get $x))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; K2: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.load (global.get $combK_addr)))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (i32.store (global.get $red_k2_addr) (i32.add (i32.load (global.get $red_k2_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 4))
          (then
            ;; K3: consume 4 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (i32.or (local.get $x) (i32.const 2)))
            (local.set $n (local.get $x))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; K3: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.load (global.get $combK2_addr)))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (i32.store (global.get $red_k3_addr) (i32.add (i32.load (global.get $red_k3_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 5))
          (then
            ;; K4: consume 5 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 5)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 5)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (i32.or (local.get $x) (i32.const 2)))
            (local.set $n (local.get $x))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; K4: consume 2 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.load (global.get $combK3_addr)))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (i32.store (global.get $red_k4_addr) (i32.add (i32.load (global.get $red_k4_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        (if (i32.ge_s (local.get $argc) (i32.const 4))
          (then
            ;; CCB: consume 4 arguments.
            (br_if $exit (i32.lt_s (local.get $argc) (i32.const 4)))
            (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
            (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
            (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
            (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
            (local.set $w (call $arg (local.get $stack) (local.get $sp) (i32.const 3)))
            (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
            (local.set $n (i32.load (i32.add (local.get $stack)
              (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
            (i32.store (local.get $n) (call $app (local.get $x) (local.get $z)))
            (i32.store offset=4 (local.get $n) (call $app (local.get $y) (local.get $w)))
            (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
            (br $top)
          ))
        ;; CCB: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (i32.load (global.get $combB_addr)) (call $app (local.get $x) (local.get $z))))
        (i32.store offset=4 (local.get $n) (local.get $y))
        (i32.store (global.get $red_ccb_addr) (i32.add (i32.load (global.get $red_ccb_addr)) (i32.const 1)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; L: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $y))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; KK: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.or (local.get $y) (i32.const 2)))
        (local.set $n (local.get $y))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; KA: consume 3 arguments.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 3)))
        (local.set $z (call $arg (local.get $stack) (local.get $sp) (i32.const 2)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 3)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (i32.store (local.get $n) (i32.or (local.get $z) (i32.const 2)))
        (local.set $n (local.get $z))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; T3 through T16 apply the final argument to the tuple fields.
        (local.set $arity (i32.sub (local.get $tag) (i32.const 34)))
        (br_if $exit (i32.lt_s (local.get $argc) (local.get $arity)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr))
          (i32.sub (local.get $arity) (i32.const 2))))
        (local.set $x (call $arg (local.get $stack) (local.get $sp)
          (i32.sub (local.get $arity) (i32.const 1))))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (i32.sub (local.get $sp) (local.get $arity))
            (i32.const 1)) (i32.const 2)))))
        (local.set $i (i32.const 0))
        (loop $fields
          (local.set $x (call $app (local.get $x)
            (call $arg (local.get $stack) (local.get $sp) (local.get $i))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br_if $fields (i32.lt_s (local.get $i)
            (i32.sub (local.get $arity) (i32.const 2)))))
        (i32.store (local.get $n) (local.get $x))
        (i32.store offset=4 (local.get $n)
          (call $arg (local.get $stack) (local.get $sp) (local.get $i)))
        (local.set $sp (i32.sub (local.get $sp) (local.get $arity)))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)
        )
        ;; TAG0 through TAG32 pass a permanent integer node to the handler.
        (br_if $exit (i32.lt_s (local.get $argc) (i32.const 2)))
        (br_if $exit (i32.le_u (i32.load (global.get $free_addr)) (i32.const 2)))
        (local.set $x (call $arg (local.get $stack) (local.get $sp) (i32.const 0)))
        (local.set $y (call $arg (local.get $stack) (local.get $sp) (i32.const 1)))
        (local.set $sp (i32.sub (local.get $sp) (i32.const 2)))
        (local.set $n (i32.load (i32.add (local.get $stack)
          (i32.shl (i32.add (local.get $sp) (i32.const 1)) (i32.const 2)))))
        (local.set $z (i32.load (i32.add (global.get $ints_addr)
          (i32.shl (i32.sub (local.get $tag) (i32.const 42)) (i32.const 2)))))
        (i32.store (local.get $n) (call $app (local.get $y) (local.get $z)))
        (i32.store offset=4 (local.get $n) (local.get $x))
        (local.set $slice (i32.sub (local.get $slice) (i32.const 1)))
        (br $top)))
    (i32.store (global.get $sp_addr) (local.get $sp))
    (i32.store (global.get $slice_addr) (local.get $slice))
    (local.get $n))
)
