;; Byte strings and foreign pointers share a 16-byte descriptor:
;; {length, data, capacity, finalizerRecord}. Capacity zero means immutable.
;; A finalizer record contains {serviceHandle, originalData}. Substrings share
;; that record and the data allocation. No primitive evaluates or collects.
;; Byte-to-list conversion produces one Cons and a deferred tail per call.
;; Failure codes 42..47 report byte bounds, mutability, UTF-8, size, or handles.

;; Wrap an existing descriptor. Kind 1 denotes a byte string; kind 0 denotes
;; a foreign pointer whose length need not be known.
(func $bs_node (param $descriptor i32) (param $kind i32) (result i32)
  (local $node i32)
  (local.set $node (call $node (global.get $T_FORPTR)))
  (i32.store offset=4 (local.get $node) (i32.or (local.get $descriptor) (local.get $kind)))
  (local.get $node))

;; Copy descriptor metadata. The two pointer fields remain collector roots.
(func $bs_copy_descriptor (param $descriptor i32) (result i32)
  (local $copy i32)
  (local.set $copy (call $blob_alloc (i32.const 16) (i32.const 10)))
  (memory.copy (local.get $copy) (local.get $descriptor) (i32.const 16))
  (local.get $copy))

;; Create a checked immutable slice. No byte buffer is copied.
(func $bs_slice (param $descriptor i32) (param $offset i32) (param $length i32) (result i32)
  (local $copy i32)
  (if (i32.load offset=8 (local.get $descriptor))
    (then (call $fail (i32.const 43)) (unreachable)))
  (if (i32.or (i32.gt_u (local.get $offset) (i32.load (local.get $descriptor)))
        (i32.gt_u (local.get $length)
          (i32.sub (i32.load (local.get $descriptor)) (local.get $offset))))
    (then (call $fail (i32.const 42)) (unreachable)))
  (local.set $copy (call $bs_copy_descriptor (local.get $descriptor)))
  (i32.store (local.get $copy) (local.get $length))
  (i32.store offset=4 (local.get $copy)
    (i32.add (i32.load offset=4 (local.get $descriptor)) (local.get $offset)))
  (call $bs_node (local.get $copy) (i32.const 1)))

;; Compare unsigned bytes, then lengths. Return -1, 0, or 1.
(func $bs_compare (param $a i32) (param $b i32) (result i32)
  (local $limit i32) (local $index i32) (local $x i32) (local $y i32)
  (local.set $limit (select (i32.load (local.get $a)) (i32.load (local.get $b))
    (i32.lt_u (i32.load (local.get $a)) (i32.load (local.get $b)))))
  (block $prefix_equal
    (loop $bytes
      (br_if $prefix_equal (i32.eq (local.get $index) (local.get $limit)))
      (local.set $x (i32.load8_u (i32.add (i32.load offset=4 (local.get $a)) (local.get $index))))
      (local.set $y (i32.load8_u (i32.add (i32.load offset=4 (local.get $b)) (local.get $index))))
      (if (i32.ne (local.get $x) (local.get $y))
        (then (return (select (i32.const -1) (i32.const 1) (i32.lt_u (local.get $x) (local.get $y))))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $bytes)))
  (i32.sub (i32.gt_u (i32.load (local.get $a)) (i32.load (local.get $b)))
    (i32.lt_u (i32.load (local.get $a)) (i32.load (local.get $b)))))

;; Append two byte strings, with an optional dot between them.
(func $bs_append (param $a i32) (param $b i32) (param $dot i32) (result i32)
  (local $length i64) (local $buffer i32) (local $split i32)
  (local.set $length (i64.add (i64.extend_i32_u (local.get $dot))
    (i64.add (i64.extend_i32_u (i32.load (local.get $a)))
      (i64.extend_i32_u (i32.load (local.get $b))))))
  (if (i64.gt_u (local.get $length) (i64.const 0x40000000))
    (then (call $fail (i32.const 45)) (unreachable)))
  (local.set $buffer (call $blob_alloc (i32.wrap_i64 (local.get $length)) (i32.const 0)))
  (local.set $split (i32.load (local.get $a)))
  (memory.copy (local.get $buffer) (i32.load offset=4 (local.get $a)) (local.get $split))
  (if (local.get $dot)
    (then (i32.store8 (i32.add (local.get $buffer) (local.get $split)) (i32.const 46))))
  (memory.copy (i32.add (local.get $buffer) (i32.add (local.get $split) (local.get $dot)))
    (i32.load offset=4 (local.get $b)) (i32.load (local.get $b)))
  (call $bytes_view (local.get $buffer) (i32.wrap_i64 (local.get $length))))

;; Append one byte to a mutable buffer. Growth preserves the descriptor.
;; An empty buffer can start at capacity zero. Other frozen buffers cannot grow.
(func $bs_append_byte (param $descriptor i32) (param $byte i32)
  (local $length i32) (local $capacity i32) (local $old i32) (local $buffer i32)
  (local.set $length (i32.load (local.get $descriptor)))
  (local.set $capacity (i32.load offset=8 (local.get $descriptor)))
  (if (i32.and (i32.eqz (local.get $capacity)) (i32.ne (local.get $length) (i32.const 0)))
    (then (call $fail (i32.const 43)) (unreachable)))
  (if (i32.ge_u (local.get $length) (local.get $capacity))
    (then
      (if (i32.gt_u (local.get $capacity) (i32.const 715827881))
        (then (call $fail (i32.const 45)) (unreachable)))
      (local.set $capacity (i32.add (local.get $capacity)
        (i32.add (i32.shr_u (local.get $capacity) (i32.const 1)) (i32.const 2))))
      (local.set $buffer (call $blob_alloc (local.get $capacity) (i32.const 0)))
      (local.set $old (i32.load offset=4 (local.get $descriptor)))
      (memory.copy (local.get $buffer) (local.get $old) (local.get $length))
      (i32.store offset=4 (local.get $descriptor) (local.get $buffer))
      (i32.store offset=8 (local.get $descriptor) (local.get $capacity))
      (if (i32.load offset=12 (local.get $descriptor))
        (then
          (i32.store offset=4 (i32.load offset=12 (local.get $descriptor)) (local.get $buffer))))
      (call $blob_free (local.get $old))))
  (i32.store8 (i32.add (i32.load offset=4 (local.get $descriptor)) (local.get $length))
    (local.get $byte))
  (i32.store (local.get $descriptor) (i32.add (local.get $length) (i32.const 1))))

;; Encode a Unicode scalar as modified UTF-8. NUL uses C0 80. Surrogates use
;; the replacement character, as the byte-string primitive does.
(func $bs_append_char (param $descriptor i32) (param $char i32)
  (if (i32.eq (i32.and (local.get $char) (i32.const 0x1ff800)) (i32.const 0xd800))
    (then (local.set $char (i32.const 0xfffd))))
  (if (i32.and (i32.gt_u (local.get $char) (i32.const 0))
        (i32.lt_u (local.get $char) (i32.const 0x80)))
    (then (call $bs_append_byte (local.get $descriptor) (local.get $char)) (return)))
  (if (i32.lt_u (local.get $char) (i32.const 0x800))
    (then
      (call $bs_append_byte (local.get $descriptor)
        (i32.or (i32.shr_u (local.get $char) (i32.const 6)) (i32.const 0xc0)))
      (call $bs_append_byte (local.get $descriptor)
        (i32.or (i32.and (local.get $char) (i32.const 63)) (i32.const 0x80)))
      (return)))
  (if (i32.lt_u (local.get $char) (i32.const 0x10000))
    (then
      (call $bs_append_byte (local.get $descriptor)
        (i32.or (i32.shr_u (local.get $char) (i32.const 12)) (i32.const 0xe0)))
      (call $bs_append_byte (local.get $descriptor)
        (i32.or (i32.and (i32.shr_u (local.get $char) (i32.const 6)) (i32.const 63)) (i32.const 0x80)))
      (call $bs_append_byte (local.get $descriptor)
        (i32.or (i32.and (local.get $char) (i32.const 63)) (i32.const 0x80)))
      (return)))
  (if (i32.ge_u (local.get $char) (i32.const 0x110000))
    (then (call $fail (i32.const 44)) (unreachable)))
  (call $bs_append_byte (local.get $descriptor)
    (i32.or (i32.shr_u (local.get $char) (i32.const 18)) (i32.const 0xf0)))
  (call $bs_append_byte (local.get $descriptor)
    (i32.or (i32.and (i32.shr_u (local.get $char) (i32.const 12)) (i32.const 63)) (i32.const 0x80)))
  (call $bs_append_byte (local.get $descriptor)
    (i32.or (i32.and (i32.shr_u (local.get $char) (i32.const 6)) (i32.const 63)) (i32.const 0x80)))
  (call $bs_append_byte (local.get $descriptor)
    (i32.or (i32.and (local.get $char) (i32.const 63)) (i32.const 0x80))))

;; Decode the first modified UTF-8 character and return {character, byteCount}.
;; Stream mode matches fromUTF8: it drops a truncated final sequence and rejects
;; nonzero overlong sequences. Head and tail use the less strict headUTF8 rules.
;; Both modes retain the existing low-six-bit handling of continuation bytes.
(func $bs_decode (param $descriptor i32) (param $stream i32) (result i32 i32)
  (local $length i32) (local $data i32) (local $first i32)
  (local $count i32) (local $index i32) (local $char i32)
  (local.set $length (i32.load (local.get $descriptor)))
  (local.set $data (i32.load offset=4 (local.get $descriptor)))
  (if (i32.eqz (local.get $length))
    (then
      (if (local.get $stream) (then (return (i32.const -1) (i32.const 0))))
      (call $fail (i32.const 44)) (unreachable)))
  (local.set $first (i32.load8_u (local.get $data)))
  (if (i32.lt_u (local.get $first) (i32.const 128))
    (then (return (local.get $first) (i32.const 1))))
  (local.set $count
    (if (result i32) (i32.eq (i32.and (local.get $first) (i32.const 0xe0)) (i32.const 0xc0))
      (then (i32.const 2))
      (else
        (if (result i32) (i32.eq (i32.and (local.get $first) (i32.const 0xf0)) (i32.const 0xe0))
          (then (i32.const 3)) (else (i32.const 4))))))
  (if (i32.lt_u (local.get $length) (local.get $count))
    (then
      (if (local.get $stream) (then (return (i32.const -1) (local.get $length))))
      (call $fail (i32.const 44)) (unreachable)))
  (if (i32.and (i32.eq (local.get $count) (i32.const 4))
        (i32.ne (i32.and (local.get $first) (i32.const 0xf8)) (i32.const 0xf0)))
    (then (call $fail (i32.const 44)) (unreachable)))
  (local.set $char (i32.and (local.get $first)
    (i32.sub (i32.shl (i32.const 1) (i32.sub (i32.const 7) (local.get $count))) (i32.const 1))))
  (local.set $index (i32.const 1))
  (block $decoded
    (loop $continuation
      (br_if $decoded (i32.eq (local.get $index) (local.get $count)))
      (local.set $char (i32.or (i32.shl (local.get $char) (i32.const 6))
        (i32.and (i32.load8_u (i32.add (local.get $data) (local.get $index))) (i32.const 63))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $continuation)))
  (if (local.get $stream)
    (then
      (if (i32.or
            (i32.and (i32.eq (local.get $count) (i32.const 2))
              (i32.and (i32.gt_u (local.get $char) (i32.const 0))
                (i32.lt_u (local.get $char) (i32.const 128))))
            (i32.or
              (i32.and (i32.eq (local.get $count) (i32.const 3))
                (i32.lt_u (local.get $char) (i32.const 0x800)))
              (i32.and (i32.eq (local.get $count) (i32.const 4))
                (i32.lt_u (local.get $char) (i32.const 0x10000)))))
        (then (call $fail (i32.const 44)) (unreachable)))))
  (local.get $char)
  (local.get $count))

;; Return a result graph, or zero when this is not a byte or pointer primitive.
(func $primitive_bytes (param $tag i32) (param $args i32) (result i32)
  (local $a i32) (local $b i32) (local $descriptor i32) (local $other i32)
  (local $length i32) (local $offset i32) (local $value i32)
  (local $result i32) (local $buffer i32) (local $world i32) (local $pointer i64)
  (local.set $a (call $value_arg (local.get $args) (i32.const 0)))
  (if (i32.eq (local.get $tag) (global.get $T_FPNEW))
    (then
      (local.set $buffer (call $pval (local.get $a)))
      (local.set $descriptor (call $blob_alloc (i32.const 16) (i32.const 10)))
      (i32.store (local.get $descriptor) (i32.const -1))
      (i32.store offset=4 (local.get $descriptor) (local.get $buffer))
      (i32.store offset=12 (local.get $descriptor)
        (call $finalizer_new (i32.const 0) (local.get $buffer)))
      (return (call $pair (call $bs_node (local.get $descriptor) (i32.const 0))
        (call $value_arg (local.get $args) (i32.const 1))))))
  (if (i32.eq (local.get $tag) (global.get $T_FPFIN))
    (then
      (local.set $value (call $pval (local.get $a)))
      (if (i32.gt_u (local.get $value) (global.get $service_count))
        (then (call $fail (i32.const 47)) (unreachable)))
      (local.set $descriptor (call $bval (call $value_arg (local.get $args) (i32.const 1))))
      (local.set $other (i32.load offset=12 (local.get $descriptor)))
      (if (i32.eqz (local.get $other))
        (then
          (local.set $other (call $finalizer_new (i32.const 0) (i32.load offset=4 (local.get $descriptor))))
          (i32.store offset=12 (local.get $descriptor) (local.get $other))))
      (i32.store (local.get $other) (local.get $value))
      (return (call $pair (call $prim (global.get $T_I))
        (call $value_arg (local.get $args) (i32.const 2))))))
  (if (i32.and (i32.ge_u (local.get $tag) (global.get $T_FPADD))
        (i32.le_u (local.get $tag) (global.get $T_BS2FP)))
    (then
      (local.set $descriptor (call $bval (local.get $a)))
      (if (i32.eq (local.get $tag) (global.get $T_FP2P))
        (then (return (call $ptr (i32.load offset=4 (local.get $descriptor))))))
      (if (i32.eq (local.get $tag) (global.get $T_BS2FP))
        (then (return (local.get $a))))
      (local.set $offset (call $ival (call $value_arg (local.get $args) (i32.const 1))))
      (if (i32.eq (local.get $tag) (global.get $T_FP2BS))
        (then
          (call $heap_check_range (i32.load offset=4 (local.get $descriptor)) (local.get $offset))
          (i32.store (local.get $descriptor) (local.get $offset))
          (return (call $bs_node (local.get $descriptor) (i32.const 1)))))
      (if (i32.load offset=8 (local.get $descriptor))
        (then (call $fail (i32.const 43)) (unreachable)))
      (local.set $pointer (i64.add (i64.extend_i32_u (i32.load offset=4 (local.get $descriptor)))
        (i64.extend_i32_s (local.get $offset))))
      (if (i64.gt_u (local.get $pointer)
            (i64.shl (i64.extend_i32_u (memory.size)) (i64.const 16)))
        (then (call $fail (i32.const 42)) (unreachable)))
      (local.set $other (call $bs_copy_descriptor (local.get $descriptor)))
      (i32.store offset=4 (local.get $other) (i32.wrap_i64 (local.get $pointer)))
      (if (i32.ne (i32.load (local.get $other)) (i32.const -1))
        (then (i32.store (local.get $other) (i32.sub (i32.load (local.get $other)) (local.get $offset)))))
      (return (call $bs_node (local.get $other) (i32.and (i32.load offset=4 (local.get $a)) (i32.const 1))))))
  (if (i32.or
        (i32.or (i32.eq (local.get $tag) (global.get $T_PACKCSTRING))
          (i32.eq (local.get $tag) (global.get $T_PACKCSTRINGLEN)))
        (i32.or (i32.eq (local.get $tag) (global.get $T_BSGRAB))
          (i32.eq (local.get $tag) (global.get $T_BSGRABLEN))))
    (then
      (local.set $buffer (call $pval (local.get $a)))
      (if (i32.or (i32.eq (local.get $tag) (global.get $T_PACKCSTRINGLEN))
            (i32.eq (local.get $tag) (global.get $T_BSGRABLEN)))
        (then
          (local.set $length (call $ival (call $value_arg (local.get $args) (i32.const 1))))
          (local.set $world (call $value_arg (local.get $args) (i32.const 2))))
        (else
          (local.set $length (call $strlen (local.get $buffer)))
          (local.set $world (call $value_arg (local.get $args) (i32.const 1)))))
      (local.set $result
        (if (result i32) (i32.or (i32.eq (local.get $tag) (global.get $T_BSGRAB))
              (i32.eq (local.get $tag) (global.get $T_BSGRABLEN)))
          (then (call $bytes_view (local.get $buffer) (local.get $length)))
          (else (call $bytes (local.get $buffer) (local.get $length)))))
      (return (call $pair (local.get $result) (local.get $world)))))
  (if (i32.eq (local.get $tag) (global.get $T_BSREPLICATE))
    (then
      (local.set $length (call $ival (local.get $a)))
      (local.set $value (call $ival (call $value_arg (local.get $args) (i32.const 1))))
      (local.set $buffer (call $blob_alloc (local.get $length) (i32.const 0)))
      (memory.fill (local.get $buffer) (local.get $value) (local.get $length))
      (return (call $bytes_view (local.get $buffer) (local.get $length)))))
  (if (i32.eq (local.get $tag) (global.get $T_BSNEW))
    (then
      (local.set $length (call $ival (local.get $a)))
      (local.set $value (call $ival (call $value_arg (local.get $args) (i32.const 1))))
      (if (i32.gt_u (local.get $length) (local.get $value))
        (then (call $fail (i32.const 45)) (unreachable)))
      (local.set $buffer (call $blob_alloc (local.get $value) (i32.const 0)))
      (local.set $result (call $bytes_view (local.get $buffer) (local.get $length)))
      (i32.store offset=8 (call $bval (local.get $result)) (local.get $value))
      (return (call $pair (local.get $result) (call $value_arg (local.get $args) (i32.const 2))))))
  (if (i32.or (i32.lt_u (local.get $tag) (global.get $T_BSAPPEND))
        (i32.gt_u (local.get $tag) (global.get $T_BSAPPENDDOT)))
    (then (return (i32.const 0))))
  (local.set $descriptor (call $bval (local.get $a)))
  (local.set $length (i32.load (local.get $descriptor)))
  (if (i32.or (i32.eq (local.get $tag) (global.get $T_BSAPPEND))
        (i32.eq (local.get $tag) (global.get $T_BSAPPENDDOT)))
    (then
      (return (call $bs_append (local.get $descriptor)
        (call $bval (call $value_arg (local.get $args) (i32.const 1)))
        (i32.eq (local.get $tag) (global.get $T_BSAPPENDDOT))))))
  (if (i32.and (i32.ge_u (local.get $tag) (global.get $T_BSEQ))
        (i32.le_u (local.get $tag) (global.get $T_BSCMP)))
    (then
      (local.set $value (call $bs_compare (local.get $descriptor)
        (call $bval (call $value_arg (local.get $args) (i32.const 1)))))
      (if (i32.eq (local.get $tag) (global.get $T_BSCMP))
        (then (return (call $ordering (local.get $value)))))
      (if (i32.eq (local.get $tag) (global.get $T_BSEQ))
        (then (return (call $boolean (i32.eqz (local.get $value))))))
      (if (i32.eq (local.get $tag) (global.get $T_BSNE))
        (then (return (call $boolean (i32.ne (local.get $value) (i32.const 0))))))
      (if (i32.eq (local.get $tag) (global.get $T_BSLT))
        (then (return (call $boolean (i32.lt_s (local.get $value) (i32.const 0))))))
      (if (i32.eq (local.get $tag) (global.get $T_BSLE))
        (then (return (call $boolean (i32.le_s (local.get $value) (i32.const 0))))))
      (if (i32.eq (local.get $tag) (global.get $T_BSGT))
        (then (return (call $boolean (i32.gt_s (local.get $value) (i32.const 0))))))
      (return (call $boolean (i32.ge_s (local.get $value) (i32.const 0))))))
  (if (i32.eq (local.get $tag) (global.get $T_BSLENGTH))
    (then (return (call $int (local.get $length)))))
  (if (i32.eq (local.get $tag) (global.get $T_BSSUBSTR))
    (then (return (call $bs_slice (local.get $descriptor)
      (call $ival (call $value_arg (local.get $args) (i32.const 1)))
      (call $ival (call $value_arg (local.get $args) (i32.const 2)))))))
  (if (i32.or (i32.eq (local.get $tag) (global.get $T_BSHEADUTF8))
        (i32.eq (local.get $tag) (global.get $T_BSTAILUTF8)))
    (then
      (call $bs_decode (local.get $descriptor) (i32.const 0))
      (local.set $offset)
      (local.set $value)
      (if (i32.eq (local.get $tag) (global.get $T_BSHEADUTF8))
        (then (return (call $int (local.get $value)))))
      (return (call $bs_slice (local.get $descriptor) (local.get $offset)
        (i32.sub (local.get $length) (local.get $offset))))))
  (if (i32.or (i32.eq (local.get $tag) (global.get $T_BSFROMUTF8))
        (i32.eq (local.get $tag) (global.get $T_BSUNPACK)))
    (then
      (if (i32.eqz (local.get $length)) (then (return (call $prim (global.get $T_K)))))
      ;; A mutable source needs one byte snapshot. Later writes must not
      ;; change the deferred list tail or invalidate its buffer during growth.
      (if (i32.load offset=8 (local.get $descriptor))
        (then
          (local.set $result (call $bytes (i32.load offset=4 (local.get $descriptor)) (local.get $length)))
          (local.set $descriptor (call $bval (local.get $result)))))
      (if (i32.eq (local.get $tag) (global.get $T_BSFROMUTF8))
        (then
          (call $bs_decode (local.get $descriptor) (i32.const 1))
          (local.set $offset)
          (local.set $value)
          (if (i32.eq (local.get $value) (i32.const -1))
            (then (return (call $prim (global.get $T_K))))))
        (else
          (local.set $offset (i32.const 1))
          (local.set $value (i32.load8_u (i32.load offset=4 (local.get $descriptor))))))
      (local.set $result (call $bs_slice (local.get $descriptor) (local.get $offset)
        (i32.sub (local.get $length) (local.get $offset))))
      (return (call $ap
        (call $ap (call $prim (global.get $T_O)) (call $int (local.get $value)))
        (call $ap (call $prim (local.get $tag)) (local.get $result))))))
  (if (i32.eq (local.get $tag) (global.get $T_BSFREEZE))
    (then
      ;; Physical capacity is an allocator detail. Keep the same data address.
      (i32.store offset=8 (local.get $descriptor) (i32.const 0))
      (return (call $pair (local.get $a) (call $value_arg (local.get $args) (i32.const 1))))))
  (if (i32.or (i32.eq (local.get $tag) (global.get $T_BSAPPBYTE))
        (i32.eq (local.get $tag) (global.get $T_BSAPPCHAR)))
    (then
      (local.set $value (call $ival (call $value_arg (local.get $args) (i32.const 1))))
      (if (i32.eq (local.get $tag) (global.get $T_BSAPPBYTE))
        (then (call $bs_append_byte (local.get $descriptor) (local.get $value)))
        (else (call $bs_append_char (local.get $descriptor) (local.get $value))))
      (return (call $pair (call $prim (global.get $T_I))
        (call $value_arg (local.get $args) (i32.const 2))))))
  (local.set $offset (call $ival (call $value_arg (local.get $args) (i32.const 1))))
  (if (i32.ge_u (local.get $offset) (local.get $length))
    (then (call $fail (i32.const 42)) (unreachable)))
  (local.set $buffer (i32.add (i32.load offset=4 (local.get $descriptor)) (local.get $offset)))
  (if (i32.eq (local.get $tag) (global.get $T_BSWRITE))
    (then
      (i32.store8 (local.get $buffer) (call $ival (call $value_arg (local.get $args) (i32.const 2))))
      (return (call $pair (call $prim (global.get $T_I))
        (call $value_arg (local.get $args) (i32.const 3))))))
  (local.set $result (call $int (i32.load8_u (local.get $buffer))))
  (if (result i32) (i32.eq (local.get $tag) (global.get $T_BSREAD))
    (then (call $pair (local.get $result) (call $value_arg (local.get $args) (i32.const 2))))
    (else (local.get $result))))
