[package]
name = "microhs-runtime"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"

[dependencies]
libc = "0.2.186"
lzma-sdk-rs = { version = "0.2301.1", features = ["decode"] }

[lib]
name = "microhs_runtime"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "mhs-rust"
path = "src/main.rs"
